(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();document.getElementById("loader-overlay");const u="https://sound-wave.b.goit.study/api/artists";let a=1;const l=8,f=document.getElementById("artists-list"),i=document.getElementById("load-more");async function d(n=1,t=8){try{i.textContent="Loading...";const s=await fetch(`${u}?page=${n}&limit=${t}`);if(!s.ok)throw new Error("Failed to fetch artists");const o=await s.json();console.log("API response:",o),Array.isArray(o.artists)?(p(o.artists),o.artists.length<t||n*t>=o.totalArtists?i.style.display="none":i.textContent="Load More"):console.error("Unexpected API structure:",o)}catch(s){console.error(s),alert("❌ Помилка завантаження артистів")}}function p(n){n.forEach(t=>{const s=document.createElement("div");s.classList.add("artist-card"),s.innerHTML=`
      <img src="${t.photo}" alt="${t.name}" class="artist-photo" />
      <div class="artist-content">
        <h3 class="artist-name">${t.name}</h3>
        <p class="artist-genres">${t.genres.join(", ")}</p>
        <p class="artist-description">${t.description||"No description available"}</p>
      </div>
    `,f.appendChild(s)})}i.addEventListener("click",()=>{a++,d(a,l)});d(a,l);
//# sourceMappingURL=index.js.map
